# -*- coding: utf-8 -*-
"""json to csv free converter.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PzRUtcpYthn_LBPblVLisGw0khL8OaVa
"""

import pandas as pd
import requests
from collections import namedtuple

url = "https://gist.githubusercontent.com/ahmu83/38865147cf3727d221941a2ef8c22a77/raw/c647f74643c0b3f8407c28ddbb599e9f594365ca/US_States_and_Cities.json"
StateCity = namedtuple('StateCity', ('state','city'))

try:
    response = requests.get(url)
    data = response.json()

    results = []
    for state in data.keys():
        for city in data[state]:
            results.append(StateCity(state, city))


    df = pd.DataFrame(results)
    df.to_csv('My data', index=False)

except Exception as e:
    print(e)